language: node_js
services:
  - docker
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - yarn

before_script:
  - docker build .
script:
  - docker-compose run client
after_script:
  - docker-compose kill
