language: node_js
services:
  - docker
branches:
  only:
    - master
env:
  - NODE_ENV=test
services:
  - mysql
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABASE prices_test;'
  -  cd server && yarn install -qy
script:
  - yarn test
