language: node_js
services:
  - docker
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - yarn

before_script:
  - docker-compose up -d
script:
  - cd client && set CI=true && yarn test -- --coverage
after_script:
  - docker-compose kill
